import { Exp } from "../interface";

export const experience: Exp[] = [
  {
    desc: `I'm a full-stack and team lead developer at GitStart YC(S-19) that helps some of the world's fastest-growing engineering teams accelerate with Pull Requests as a Service. Assign us on tickets, review incoming Pull Requests, only pay for those you merge. You can thus save time, flexibly scale engineering capacity and accelerate within weeks.`,
    name: "GitStart YC(S-19)",
    year: "2021-To date",
    projects: [
      { project: "Company website,", url: "https://www.gitstart.com/" },
      { project: "Developer portal,", url: "https://www.gitstart.dev/" },
      { project: "Sourcegraph,", url: "https://about.sourcegraph.com/" },
      { project: "Superbase,", url: "https://supabase.com/" },
      { project: "Cypress", url: "https://www.cypress.io/" },
    ],
    techStack: [
      "TypeScript",
      "React.js",
      "Nodejs/express",
      "Docker,",
      "kubernetes",
      "Cypress,",
      "Zustand",
      "Amazon-RDS",
      "GraphQL",
      "CSS3",
      "SASS",
      "Storybook",
      "styled-components",
      "Webpack",
      "Go lang",
      "Bash",
      "Amazon S3",
      "Redis",
      "Github Actions",
      "PostgreSQL",
      "Firebase",
    ],
  },
  {
    desc: `I was full stack software Engineer at netbritz.com which is the new modern social media with almost all features of modern social App. It was engeneered with full JavaScript stack which is Reactjs, Redux, Apollo-client, Apollo-server, Expressjs, and MongoDb.`,
    name: "Netbritz",
    year: "2018-To 2021",
    projects: [{ project: "Company website", url: "https://netbritz.com/" }],
    techStack: [
      "TypeScript",
      "React.js",
      "Nodejs/express",
      "Docker",
      "kubernetes",
      "Cypress",
      "Redux",
      "GraphQL",
      "CSS3",
      "SASS",
      "Storybook",
      "styled-components",
      "Webpack",
      "Amazon S3",
      "Github Actions",
      "PostgreSQL",
      "Next.js",
      "Firebase",
      "D3.js",
    ],
  },
  {
    desc: `I was Fullstack developer and team leader resposible for designing, developing and maintaining new user interfaces for both mobile and desktop, developing and maintaining API's, designing and developing databases among others.`,
    name: "Wakanda Great View Holidays",
    year: "2017-2018",
    projects: [
      { project: "Company website", url: "http://wakandaviewholidays.com/" },
    ],
    techStack: [
      "PHP/Laravel",
      "JavaScript",
      "AWS-S3",
      "PostgreSQL",
      "SASS",
      "Material Design",
    ],
  },
];
